{
  "branding": {
    "logo": {
      "url": "media/e369a88d-17db-4e57-ab63-10d90566ac5b.png",
      "allowToShowLogo": false
    },
    "alternativeLogo": {
      "url": "media/e369a88d-17db-4e57-ab63-10d90566ac5b.png"
    },
    "colors": [
      {
        "key": "main-color",
        "value": "#F0754D"
      },
      {
        "key": "cta-button-color",
        "value": "#F0754D"
      },
      {
        "key": "content-body-color",
        "value": "#fff"
      },
      {
        "key": "correct-color",
        "value": "#65C86D"
      },
      {
        "key": "incorrect-color",
        "value": "#F85D67"
      },
      {
        "key": "text-color",
        "value": "#363E4E"
      },
      {
        "key": "button-text-color",
        "value": "#fff"
      },
      {
        "key": "cover-bg-overlay-text-color",
        "value": "#363E4E"
      }
    ],
    "background": {
      "header": {
        "brightness": null,
        "color": null,
        "image": {
          "url": "media/53ea7c17-d14a-44cc-848a-8d724dfeaf65.png",
          "option": "fullscreen"
        },
        "coverOverlay": {
          "enabled": false,
          "color": "#F0754D",
          "opacity": 0.8
        }
      },
      "body": {
        "switchable": null,
        "enabled": true,
        "brightness": null,
        "color": "#FFFFFF",
        "texture": null
      }
    }
  },
  "fonts": [
    {
      "place": "none",
      "key": "main-font",
      "fontFamily": "Qanelas-Soft"
    },
    {
      "place": "none",
      "key": "secondary-font",
      "fontFamily": "Qanelas-Soft"
    },
    {
      "place": "none",
      "key": "Heading1",
      "size": 32,
      "fontFamily": "Qanelas-Soft",
      "color": "#363e4e",
      "fontWeight": 600,
      "textDecoration": "none",
      "fontStyle": "normal",
      "textBackgroundColor": null,
      "isGeneralSelected": true,
      "isSecondarySelected": false,
      "isGeneralColorSelected": true
    },
    {
      "place": "none",
      "key": "Heading2",
      "size": 26,
      "fontFamily": "Qanelas-Soft",
      "color": "#363e4e",
      "fontWeight": 600,
      "textDecoration": "none",
      "fontStyle": "normal",
      "textBackgroundColor": null,
      "isGeneralSelected": true,
      "isSecondarySelected": false,
      "isGeneralColorSelected": true
    },
    {
      "place": "none",
      "key": "Heading3",
      "size": 22,
      "fontFamily": "Qanelas-Soft",
      "color": "#363e4e",
      "fontWeight": 600,
      "textDecoration": "none",
      "fontStyle": "normal",
      "textBackgroundColor": null,
      "isGeneralSelected": true,
      "isSecondarySelected": false,
      "isGeneralColorSelected": true
    },
    {
      "place": "none",
      "key": "Heading4",
      "size": 20,
      "fontFamily": "Qanelas-Soft",
      "color": "#363e4e",
      "fontWeight": 600,
      "textDecoration": "none",
      "fontStyle": "normal",
      "textBackgroundColor": null,
      "isGeneralSelected": true,
      "isSecondarySelected": false,
      "isGeneralColorSelected": true
    },
    {
      "place": "none",
      "key": "Normal",
      "size": 18,
      "fontFamily": "IowanOldSt-BT",
      "color": "#363e4e",
      "fontWeight": "normal",
      "textDecoration": "none",
      "fontStyle": "normal",
      "textBackgroundColor": null,
      "isGeneralSelected": false,
      "isSecondarySelected": true,
      "isGeneralColorSelected": true
    },
    {
      "place": "none",
      "key": "Quote",
      "size": 24,
      "fontFamily": "IowanOldSt-BT",
      "color": "#363e4e",
      "fontWeight": 400,
      "textDecoration": "none",
      "fontStyle": "italic",
      "textBackgroundColor": null,
      "isGeneralSelected": false,
      "isSecondarySelected": true,
      "isGeneralColorSelected": true
    },
    {
      "place": "none",
      "key": "Highlighted",
      "size": 18,
      "fontFamily": "IowanOldSt-BT",
      "color": "#fff",
      "fontWeight": "normal",
      "textDecoration": "none",
      "fontStyle": "normal",
      "textBackgroundColor": "#F0754D",
      "isGeneralSelected": false,
      "isSecondarySelected": true,
      "isGeneralColorSelected": false
    },
    {
      "place": "none",
      "key": "links",
      "size": 18,
      "fontFamily": "IowanOldSt-BT",
      "color": "#F0754D",
      "fontWeight": "normal",
      "textDecoration": "underline",
      "fontStyle": "normal",
      "textBackgroundColor": null,
      "isGeneralSelected": false,
      "isSecondarySelected": true,
      "isGeneralColorSelected": false
    }
  ],
  "layout": {
    "selected": "onePage",
    "courseNavigationSettings": {
      "selected": "clickNext"
    }
  },
  "languages": {
    "selected": "fr",
    "customSelected": "en",
    "customTranslations": {
      "[passed]": "Réussi",
      "[not passed yet]": "Pas encore réussi",
      "[go to results]": "Aller aux résultats",
      "[next section]": "Section suivante",
      "[next]": "Suivant",
      "[submit]": "Envoyer",
      "[try again]": "Réessayer",
      "[survey question hint]": "* La réponse n'aura pas d'impact sur votre progression",
      "[page counter caption]": "Page {index} sur {total}",
      "[your answer has been stored]": "Votre réponse a été sauvegardée !",
      "[your answer is empty and was not stored]": "Votre réponse est vide, elle n'a pas été sauvegardée !",
      "[thats correct]": "Correct !",
      "[thats incorrect]": "Incorrect !",
      "[hint]": "Indice",
      "[show hint]": "Montrer les indices",
      "[hide hint]": "Cacher les indices",
      "[congratulations]": "Félicitations",
      "[course is not passed yet]": "La formation n'est pas réussie pour l'instant.",
      "[you passed the course successfully]": "Vous avez réussi la formation.",
      "[you have not passed the course yet]": "Vous n'avez pas encore réussi la formation.",
      "[you correctly answered X questions out of Y]": "Vous avez répondu correctement à {correctQuestionsCount} sur {totalQuestionsCount} question(s).",
      "[continue course]": "Continuer la formation",
      "[start section]": "Démarrer la section",
      "[statement question true text]": "Vrai",
      "[statement question false text]": "Faux",
      "[drag and drop question image]": "Glisser-déposer l'image de la question",
      "[download]": "Télécharger",
      "[back home button]": "Retour à la page de démarrage",
      "[navigation section]": "Section de navigation",
      "[aria label start section]": "Aller à la section",
      "[expanded nav section]": "Section de navigation étendue",
      "[open section items]": "Ouvrir la section",
      "[close section items]": "Fermer la section",
      "[hamburger aria label expanded]": "Réduire le menu",
      "[hamburger aria label collapse]": "Étendre le menu",
      "[aria label status text]": "Section de statut",
      "[aria label zoom button]": "Zoomer sur l'image",
      "[results]": "Résultats",
      "[placeholder textarea]": "Saisir votre réponse ici...",
      "[close popup]": "Fermer la fenêtre contextuelle",
      "[alt answer image]": "Répondre",
      "[aria label rocket]": "Fusée",
      "[aria label trophy]": "Trophée",
      "[title for results page]": "Résultats",
      "[aria label gallery popup]": "Afficher la galerie",
      "[aria label question icon]": "Pas encore réussi",
      "[aria label question icon ok]": "Passé de manière correcte",
      "[aria label question icon non]": "Passé de manière incorrecte",
      "[section page title]": "Sections",
      "[questions page title]": "Questions",
      "[content page title]": "Contenu",
      "[login]": "Se connecter",
      "[signup]": "S'inscrire",
      "[alt logo login]": "Type de logo",
      "[create account]": "Créer un compte",
      "[sign up form text]": "Veuillez créer un compte afin de pouvoir continuer vos formations à tout moment sur n'importe quel appareil.",
      "[sign up button]": "S'inscrire",
      "[sign up with]": "ou s'inscrire via",
      "[login with]": "ou continuer via",
      "[login form text]": "Veuillez vous connecter afin de pouvoir continuer à tout moment sur n'importe quel appareil.",
      "[login button]": "Se connecter",
      "[welcome]": "Bienvenue",
      "[forgot pass]": "J'ai oublié mon mot de passe",
      "[footnote]": "* En donnant votre autorisation au moyen de l'une des options, vous acceptez que vos résultats et scores soient enregistrés. Ces résultats ne seront visibles que par l'organisateur (auteur) de cette formation.",
      "[btn FB label]": "Continuer via Facebook",
      "[btn LI label]": "Continuer via LinkedIn",
      "[btn G label]": "Continuer via Google+",
      "[label eye icon show]": "Afficher le mot de passe",
      "[label eye icon hide]": "Masquer le mot de passe",
      "[skip step]": "Sauter cette étape, commencer en mode anonyme",
      "[title for login page]": "Page de connexion",
      "[title for signup page]": "Page d'inscription",
      "[error email input]": "Saisir une adresse e-mail valide",
      "[welcome without LS]": "Veuillez vous présenter",
      "[login form text without LS]": "Vous pourrez à tout moment ouvrir à nouveau la formation et reprendre là où vous en étiez.",
      "[validation pass space]": "Aucun espace",
      "[validation pass count char]": "Au moins 7 caractères",
      "[have account]": "Vous avez déjà un compte ?",
      "[dont have account]": "Vous n'avez pas de compte ?",
      "[signup here]": "S'inscrire ici",
      "[user exist]": "Ce compte existe déjà. Cliquer sur Se connecter et essayer à nouveau.",
      "[error login email]": "La combinaison de l'email et du mot de passe n'existe pas.",
      "[error login pass]": "Veuillez réessayer ou réinitialiser votre mot de passe.",
      "[continue on this device]": "Continuer à tout moment sur n'importe quel périphérique",
      "[visit the page]": "Visiter la page",
      "[send me the link]": "M'envoyer le lien",
      "[get secret link to]": "Obtenir un lien secret sur l'adresse {email},",
      "[get a secret link to explanation]": "pour pouvoir vous connecter à la formation instantanément",
      "[close course]": "Clôturer la formation",
      "[continue later aria label]": "Continuer plus tard",
      "[aria label secret link]": "E-mail avec un lien secret",
      "[reset password link sent success]": "Nous vous avons envoyé un e-mail avec les instructions pour réinitialiser votre mot de passe.",
      "[secret link email sent success]": "L'e-mail a bien été envoyé.",
      "[error secret link email sending]": "Un problème est survenu lors de l'envoi de l'e-mail. Veuillez essayer à nouveau.",
      "[scenario tooltip text]": "Le scénario n'est pas encore terminé.\n Vous devez le terminer avant de le transmettre.",
      "[scenario submitted]": "Le scénario a été transmis",
      "[the owner of the course has limited the access]": "Le propriétaire de la formation a limité l'accès",
      "[back to login]": "Retour à la page de connexion",
      "[title for noaccess page]": "Accès limité",
      "[remember me]": "Se souvenir de moi",
      "[placeholder text input]": "Saisir votre réponse",
      "[placeholder dropdown]": "Choisir votre réponse",
      "[label your choice is]": "Votre choix est le suivant :",
      "[hotspot content image alt]": "Contenu de zone d'intérêt",
      "[hotspot open popover]": "Zone d'intérêt – Ouvrir fenêtre contextuelle",
      "[logout]": "Se déconnecter",
      "[continue later with link]": "Continuer plus tard avec un lien",
      "[submit results]": "Soumettre les résultats",
      "[aria label close course popup]": "Clôturer la formation",
      "[download certificate]": "Télécharger le certificat",
      "[certificate file name]": "Certificat de formation",
      "[passed section title]": "Bien joué !",
      "[passed section]": "Vous avez réussi cette section ! Continuez comme ça !",
      "[you need to answer X questions out of Y]": "Vous devez répondre correctement à {correctQuestionsCount} questions sur {totalQuestionsCount} pour réussir cette section.",
      "[close popover]": "Fermer la fenêtre contextuelle",
      "[certificate failed load]": "Une erreur s'est produite lors du téléchargement du certificat. Veuillez réessayer.",
      "[rate the course]": "Comment évalueriez-vous votre expérience globale tout au long de cette formation ?",
      "[poor rating]": "Médiocre",
      "[excellent rating]": "Excellente",
      "[you gave a rate of]": "Vous donnez une note de",
      "[course score reason]": "Pour quelle(s) raison(s) avez-vous donné ce score ?",
      "[aria label rate figure]": "Noter",
      "[thank for feedback]": "Nous vous remercions de vos commentaires !",
      "[back to the results]": "Retour aux résultats",
      "[aria label close nps popup]": "Vous donnez à cette formation la note de",
      "[learning objective]": "Objectif d'apprentissage",
      "[hide learning objective]": "Masquer l'objectif d’apprentissage",
      "[show learning objective]": "Objectif d’apprentissage",
      "[overview]": "Aperçu",
      "[start new attempt]": "Faire une nouvelle tentative",
      "[start new attempt title]": "Désirez-vous faire une nouvelle tentative ?",
      "[aria label start new attempt popup]": "Faire une nouvelle tentative",
      "[start new attempt text]": "Quand vous procédez à une nouvelle tentative, vous ne pouvez plus voir la tentative précédente",
      "[back to the course]": "Retour à la formation",
      "[section overview]": "Aperçu de la section",
      "[x out of y sections passed]": "{CountSectionsSuccess} SUR {countSections} SECTIONS RÉUSSIES",
      "[you complete x]": "Vous avez réussi avec un score de {percentSuccess} %",
      "[reach x to pass the course]": "Atteindre {mustPercentSuccess} % pour réussir la formation",
      "[error name input]": "! Veuillez saisir un non valide",
      "[post comment]": "Publier le commentaire",
      "[cancel]": "Annuler",
      "[please identify yourself]": "Veuillez vous identifier",
      "[got it]": "J'ai compris",
      "[click to leave a comment]": "Pour laisser un commentaire, cliquer sur l'icône en regard de l'élément concerné.",
      "[comment area]": "Zone de commentaires",
      "[not found text]": "Désolé, la page demandée est introuvable. Veuillez vérifier si l’URL est correcte, utiliser la navigation ci-dessus ou cliquer sur le lien « Accueil ».",
      "[home]": "Accueil",
      "[not found title]": "Introuvable",
      "[error comment sending]": "Un problème est survenu. Veuillez essayer à nouveau.",
      "[click on the plus to define the match]": "Cliquer sur le plus pour définir la correspondance",
      "[choose option]": "Choisir l'option",
      "[continue course later]": "Continuer la formation plus tard",
      "[note that]": "Noter les points suivants :",
      "[note]": "Vous pouvez à tout moment ouvrir à nouveau la formation et reprendre là où vous en étiez",
      "[ok close course]": "OK, terminer la formation",
      "[cancel go back to the course]": "Annuler, retour à la formation",
      "[name]": "Nom",
      "[email]": "E-mail",
      "[password]": "Mot de passe",
      "[user menu submit result]": "Soumettre les résultats",
      "[placeholder dropdown for]": "Choisir votre réponse pour",
      "[drag and drop question all texts are placed]": "Vide",
      "[my courses]": "Mes formations",
      "[close course text]": "Vous pouvez maintenant fermer l'onglet de votre navigateur ou retourner à vos formations",
      "[close lti course text]": "Vous pouvez maintenant fermer l'onglet de votre navigateur",
      "[404 file not found]": "404 : Fichier introuvable",
      "[remaining attempts]": "Tentatives restantes :",
      "[x out of y sections taken]": "{countSectionsSuccess} section(s) sur {countSections} parcourue(s)",
      "[x out of y questions answered]": "{countAnsweredQuestions} question(s) sur {countQuestions} répondues",
      "[x y questions answered]": "{countAnsweredQuestionsInSection}/{countQuestionsInSection} questions répondues",
      "[x y answered correctly]": "{countCorrectlyAnsweredQuestionsInSection}/{countQuestionsInSection} réponses correctes",
      "[submit all answers]": "Soumettre toutes les réponses",
      "[you did not answer all questions]": "Vous n'avez pas répondu à toutes les questions",
      "[not passed]": "Non réussi",
      "[failed section title]": "La section n'a pas été achevée avec succès",
      "[failed section x y]": "Pour réussir cette section, vous devez répondre correctement à au moins {countCorrectlyAnsweredQuestionsInSection} questions sur {countQuestionsInSection}.",
      "[course ready to start text]": "Je suis prêt",
      "[questions]": "question(s)",
      "[attempts]": "tentative(s)",
      "[min]": "min",
      "[time]": "heure",
      "[question pool introduction text without timer and attempts x y]": "Vous devez répondre à {questionPoolSize} questions. Pour réussir la formation, vous devez obtenir {masteryScore} %.",
      "[question pool introduction text with timer and attempts p q r s]": "Vous devez répondre à {questionPoolSize} questions dans cette série et vous disposez de {timer} minutes pour ce faire. Pour réussir la formation, vous disposez de {remainedAttempts} tentatives et vous devez obtenir {masteryScore} %.",
      "[question pool introduction text with timer x y z]": "Vous devez répondre à {questionPoolSize} questions dans cette série et vous disposez de {timer} minutes pour ce faire. Pour réussir la formation, vous devez obtenir {masteryScore} %.",
      "[question pool introduction text with attempts x y z]": "Vous devez répondre à {questionPoolSize} questions dans cette série. Pour réussir la formation, vous disposez de {remainedAttempts} tentatives et vous devez obtenir {masteryScore} %.",
      "[question pool timer intro text]": "Le minuteur démarrera après que vous ayez pressé le bouton « Je suis prêt ».",
      "[good luck]": "Bonne chance !",
      "[question pool counter caption]": "Question {index} sur {total}",
      "[question pool passed]": "Vous avez réussi la formation ! Continuez comme ça !",
      "[check connection]": "Il semble que la connexion avec le serveur ait été perdue",
      "[close course connection lost]": "Si la connexion ne se rétablit pas, veuillez vérifier votre connexion Internet. Si le problème persiste, veuillez fermer la formation et réessayer plus tard. \n Vous pourrez reprendre la formation là où vous l'avez interrompue.",
      "[trying to reconnect]": "Nous essayons de rétablir la connexion...",
      "[reconnected successfully]": "La connexion a été rétablie avec succès.",
      "[connection note]": "* Remarque :",
      "[note use same course]": "plus tard, vous pouvez utiliser le même lien de formation ou retrouver la formation sur Easygenerator for Learners",
      "[something went wrong title]": "Un problème est survenu",
      "[logo]": "Type de logo",
      "[start over]": "Recommencer",
      "[start over description]": "La formation a été modifiée par l'auteur pendant que vous y travailliez. En raison de ces changements, vous devrez recommencer en cliquant sur le bouton ci-dessous.",
      "[aria label start over popup]": "Recommencer",
      "[questions - second variation]": "Questions",
      "[you can close browser tab]": "Vous pouvez maintenant fermer l'onglet de votre navigateur",
      "[checklist]": "Checklist",
      "[completed]": "terminé",
      "[close checklist]": "Fermer une Checklist",
      "[title for checklist page]": "Checklist",
      "[course is not passed]": "La formation n'a pas été réussie",
      "[you have not passed the course]": "Vous n'avez pas réussi la formation.",
      "[all attempts has been used]": "Toutes les tentatives ont été utilisées.",
      "[aria label failed course]": "Échec de la formation",
      "[how to]": "How-to",
      "[close how to]": "Fermer",
      "[x question remaining]": "{remainingQuestions} question(s) restante(s)",
      "[you successfully passed the course with a score of x]": "Vous avez réussi la formation avec un score de {score}.",
      "[aria label timeout image alt]": "Dépassement de délai",
      "[timed out title]": "Le temps est écoulé",
      "[timed out description]": "Cliquez sur le bouton ci-dessous pour voir les résultats",
      "[aria label timed out popup]": "Délai dépassé",
      "[timer]": "Minuteur",
      "[minutes]": "minutes",
      "[section x of y]": "Section {index} sur {total}",
      "[course]": "Formation",
      "[learner agreement signup]": "En cliquant sur «S’inscrire», j’accepte les conditions suivantes d’Easygenerator",
      "[eula]": "Accord de licence utilisateur final (EULA)",
      "[error signup common]": "Une erreur est survenue lors de l'exécution de la demande. Veuillez réessayer.",
      "[gdpr text]": "Easygenerator stocke vos données au sein de l'Union européenne",
      "[skip to content]": "Aller au contenu",
      "[close anonymous user course text]": "Vous pouvez maintenant fermer l'onglet de votre navigateur",
      "[question pool introduction text zero question]": "Vous devez répondre à 0 question(s) dans cette série.",
      "[you completed X out of Y sections]": "Vous avez complété {correctSectionsCount} sur {totalSectionsCount} sections.",
      "[one attempt to complete course]": "Vous n'avez qu'une seule tentative pour terminer ce cours",
      "[only this attempt left]": "Il ne vous reste que cette tentative",
      "[one attempt to complete question]": "Vous n'avez qu'une seule tentative pour répondre à cette question",
      "[exit course]": "Quitter la formation",
      "[overall answer x y questions z]": "Pour valider la totalité du cours, vous devez répondre correctement à au moins {questionCountToReachMasteryScore} questions sur {affectProgressQuestionsCount} ({masteryScoreValue}%)",
      "[overall answer x y items z]": "Pour valider la totalité du cours, vous devez compléter correctement au moins {questionCountToReachMasteryScore} éléments sur {affectProgressQuestionsCount} ({masteryScoreValue}%)",
      "[overall answer x y content z]": "Pour valider la totalité du cours, vous devez lire au moins {questionCountToReachMasteryScore} sections du contenu {affectProgressQuestionsCount} ({masteryScoreValue}%)",
      "[you correctly completed X items out of Y]": "Vous avez complété correctement {correctQuestionsCount} élément(s) sur {totalQuestionsCount}.",
      "[aria label loader]": "Dispositif de chargement",
      "[configuration error]": "Un pépin est apparemment présent dans la configuration de la formation.",
      "[invalid lrs configuration]": "Vous ne pouvez pas accéder à cette formation, car les paramètres liés aux résultats sont incomplets. Veuillez contacter l'auteur de la formation pour obtenir de l'aide.",
      "[accessibility mode]": "Mode accessibilité",
      "[accessibility mode enabled]": "Vous êtes maintenant en mode accessibilité.",
      "[default]": "Par défaut",
      "[wcag feature description]": "Cliquez sur {link} pour lire la description complète de tous les paramètres d'accessibilité.",
      "[contrast theme]": "Thème de contraste",
      "[readable font]": "Police lisible",
      "[font size adjustment]": "Réglage de la taille de la police",
      "[dyslexia font]": "Police pour dyslexiques",
      "[seizure safe]": "Protection contre les grippages",
      "[contrast theme description]": "Appliquez un thème de couleur de contraste élevé pour augmenter le contraste de l'interface de la formation et pour faciliter la lisibilité. Un thème de contraste élevé utilise une petite palette de couleurs contrastées (bleu foncé, par exemple) qui rend l'interface plus visible, tout en vous permettant d'apprécier la conception élégante des formations Easygenerator.",
      "[readable font description]": "Sélectionnez l'option « Police lisible » pour appliquer une police Arial basique, simple et sans ornement. Arial ne comporte pas de décorations supplémentaires ou de fioritures, ce qui en fait une des polices les plus accessibles et les plus faciles à lire.",
      "[font size adjustment description]": "L'option « Réglage de la taille de la police » vous permet d'augmenter ou de diminuer la taille du texte sans faire de zoom avant sur le reste d'une page. Vous pouvez passer facilement entre une taille de police par défaut, grande, extra-grande et énorme du contenu en appuyant sur les boutons (+) et (-).",
      "[dyslexia font description]": "Appliquez une police « Dyslexie » spécialement conçue pour améliorer la visibilité des lettres. Cette police facilite la distinction entre les formes des lettres et caractères différents. Elle offre en plus une meilleure expérience de lecture.",
      "[seizure safe description]": "Activez l'option « Protection contre les grippages » pour réduire l'animation et les couleurs brillantes dans les images et la vidéo. Le mode « Protection contre les grippages » met fin aux clignotements pour éliminer le risque de grippages ou d'autres réactions physiques incapacitantes.",
      "[wcag feature description link]": "ici",
      "[aria label wcag feature description]": "Cliquez ici pour lire une description complète de tous les paramètres d'accessibilité.",
      "[hi there]": "Bonjour,",
      "[hi username]": "Bonjour {userName},",
      "[click to flip]": "cliquer pour retourner",
      "[wcag description title]": "Description des réglages d'accessibilité",
      "[large]": "Grand",
      "[extra large]": "Très grand",
      "[huge]": "Hyper grand",
      "[didnt receive login link]": "Vous n'avez pas reçu d'e-mail avec le lien de connexion ?",
      "[resend login link]": "Renvoyer le lien à la même adresse e-mail",
      "[use the login link from email]": "Utilisez le lien de connexion reçu par e-mail ({email}) pour accéder à l'historique des commentaires et des réponses.",
      "[login link sent to email]": "Le lien de connexion a été envoyé avec succès à l'adresse e-mail : {email}. Vous pouvez toujours publier des commentaires, mais vous devrez vous connecter pour accéder à l'historique des commentaires et des réponses.",
      "[comment resolved by author]": "Le commentaire a été résolu par l'auteur ou le coauteur de la formation...",
      "[comment deleted by author]": "Le commentaire a été supprimé par l'auteur ou le coauteur de la formation...",
      "[reply resolved by author]": "La réponse a été résolue par l'auteur ou le coauteur de la formation...",
      "[reply deleted by author]": "La réponse a été supprimée par l'auteur ou le coauteur de la formation...",
      "[add reply]": "Ajouter la réponse",
      "[post reply]": "Publier la réponse",
      "[review you will receive the login link]": "Vous recevrez le lien de connexion pour accéder à l'historique de vos commentaires et des réponses de l'auteur de la formation.",
      "[continue]": "Continuer",
      "[get login link]": "Obtenir un lien de connexion",
      "[write a comment]": "Écrire un commentaire",
      "[author notified of comment]": "L'auteur a été informé de votre commentaire",
      "[login link resent]": "Le lien de connexion a été renvoyé avec succès à l'adresse e-mail {email}. Vérifiez votre dossier de courrier indésirable pour vous assurer qu'il ne s'y trouve pas.",
      "[delete comment]": "Supprimer le commentaire",
      "[delete reply]": "Supprimer la réponse",
      "[X replies]": "{x} réponses",
      "[reply]": "Répondre",
      "[contact]": "Veuillez contacter {supportEmail}",
      "[end session]": "Terminer la session",
      "[x years ago]": "il y a {x} an(s)",
      "[x months ago]": "il y a {x} mois",
      "[x days ago]": "il y a {x} jour(s)",
      "[x hours ago]": "il y a {x} heure(s)",
      "[x minutes ago]": "il y a {x} minute(s)",
      "[less than a minute ago]": "il y a moins d'une minute",
      "[a few seconds ago]": "il y a quelques secondes",
      "[validation enter full name]": "Le nom complet doit inclure votre nom et prénom",
      "[no replies yet]": "Pas encore de réponses",
      "[delete comment confirmation]": "Supprimer toute la conversation ?",
      "[delete]": "Effacer",
      "[reply was deleted]": "La réponse a été supprimée…",
      "[undo]": "Annuler",
      "[delete forever]": "Supprimer définitivement",
      "[close]": "Fermer",
      "[no questions found]": "Cette formation ne comprend aucune question",
      "[add new comment]": "Ajouter un nouveau commentaire",
      "[study time]": "Temps d'apprentissage",
      "[author]": "Auteur",
      "[question hint]": "Indice",
      "[course overview]": "Aperçu de la formation",
      "[section]": "Section",
      "[download file]": "TÉLÉCHARGER LE FICHIER",
      "[flipcard]": "Carte à retourner",
      "[front]": "Recto",
      "[back]": "Verso",
      "[visit page]": "Visiter la page",
      "[answer options for numbered inputs below]": "Options de réponse pour les entrées numérotées ci-dessous",
      "[match the answers with data below]": "Faites correspondre les réponses aux données ci-dessous",
      "[put correct data in boxes on the image]": "Déplacez les données correctement dans les cases de l'image",
      "[rank answers in input below]": "Classez les réponses dans les catégories ci-dessous",
      "[resource]": "Ressource",
      "[you have reached the end of the course]": "Vous avez atteint la fin de la formation",
      "[published date]": "Date de publication",
      "[video not available in pdf]": "La vidéo n’est pas disponible au format PDF",
      "[audio not available in pdf]": "L’audio n’est pas disponible au format PDF",
      "[content not available in pdf version]": "Le contenu ci-joint n'est pas disponible au format PDF. Veuillez utiliser le lien ci-dessous pour visualiser le fichier.",
      "[you have reached the end of the resource]": "Vous avez atteint la fin de la ressource",
      "[one reply]": "{x} réponse",
      "[you read X out of Y pages]": "Vous avez répondu correctement à {correctQuestionsCount} sur {totalQuestionsCount} question(s).",
      "[aria label star rating]": "Trophée",
      "[change email and name]": "Changer l’adresse e-mail et le nom",
      "[submit result]": "Soumettre vos résultats",
      "[results are submitted]": "Vos résultats ont été soumis.",
      "[success results submitted]": "Vos résultats ont bien été soumis. Vous pouvez fermer le cours maintenant.",
      "[aria label passed]": "Réussi",
      "[You have completed X out of Y required sections]": "Vous avez terminé {correctSectionsCount} sur {totalSectionsCount} sections demandées. Continuez votre cours afin de terminer les sections restantes.",
      "[close course after submit]": "Vous pouvez fermer le cours maintenant.",
      "[completed all sections]": "Vous avez terminé l'ensemble des sections. N'oubliez pas de soumettre vos résultats avant de fermer cette page.",
      "[submit course results]": "N'oubliez pas de soumettre vos résultats avant de fermer cette page.",
      "[step X of Y]": "Étape {currentStepCount} sur {totalStepCount}",
      "[aria label not-passed]": "Non réussi",
      "[read X out of Y pages successfully]": "Vous avez réussi le cours. Vous avez terminé {correctQuestionsCount} sur un total de {totalQuestionsCount} page(s). N'oubliez pas de soumettre vos résultats avant de fermer cette page.",
      "contentArea": "zone de contenu",
      "[submit results course]": "Si vous soumettez vos résultats maintenant, votre cours ne sera pas validé.",
      "[completed overall course]": "Vous avez terminé le cours. N'oubliez pas de soumettre vos résultats avant de fermer cette page.",
      "reviewSpotContextDescription": "Commentaires sur : {contextType}",
      "titleOfTheCourse": "titre de la formation",
      "section": "Section",
      "questionTitle": "Question",
      "hint": "indice",
      "contentTitleLabel": "Titre du contenu",
      "positiveLearnerScore": "score positif de l’apprenant",
      "negativeLearnerScore": "score négatif de l’apprenant",
      "questionTitleLabel": "Titre de la question",
      "singleChoiceQuestion": "question à choix unique",
      "questionContent": "Instruction de la question",
      "answerOptions": "Options de réponse",
      "explanationForAnswerOptions": "explication pour les options de réponse",
      "questionFeedback": "Retour d'information",
      "multiChoiceQuestion": "question à choix multiple",
      "singleSelectImage": "Choix d’image unique",
      "fillInTheBlankQuestion": "texte à trous",
      "textMatchingQuestion": "question d’association",
      "dragNDropQuestion": "question glisser-déposer",
      "statementQuestion": "Question vrai/faux",
      "hotspotQuestion": "zone réactive",
      "openQuestion": "Question ouverte",
      "rankingTextQuestion": "question de classement",
      "[complete remaining attempts]": "Veuillez terminer la ou les tentatives restantes.",
      "[ShowContentDisabledError]": "Vous avez désactivé le paramètre \"Afficher les pages de contenu\" dans l'onglet de configuration. Veuillez l'activer pour afficher la page de contenu",
      "voiceOver": "Voix off",
      "[error message for learners]": "Veuillez contacter l'auteur de la formation ou votre équipe L&amp;D",
      "correctOption": "Option correcte",
      "viewCorrectAnswers": "Voir les réponses correctes",
      "[details]": "Détails",
      "[aria label start question]": "Accéder à la question",
      "[correct]": "Correct",
      "[incorrect]": "Incorrect",
      "[answered]": "Répondu",
      "[not passed this course]": "Vous n'avez pas encore réussi cette formation",
      "[not yet completed all the sections]": "Vous n'avez pas encore complété toutes les sections.",
      "[see results]": "Voir les résultats",
      "[progress]": "Progression",
      "[category x]": "Catégorie {x} :",
      "[no cards in category]": "Aucune carte dans cette catégorie",
      "[allItemsPlaced]": "Aucune carte restante",
      "[no cards added]": "Aucune carte n'a été ajoutée par l'auteur",
      "[embed content not available in pdf version]": "Le contenu intégré n'est pas disponible au format PDF. Veuillez utiliser le lien ci-dessous pour le visualiser.",
      "[successfully passed]": "Vous avez réussi cette formation.",
      "[you have correctly answered X questions out of Y]": "Vous avez répondu correctement à {correctQuestionsCount} question(s) sur {totalQuestionsCount}.",
      "[not passed course yet]": "Vous n'avez pas encore réussi cette formation.",
      "[oh no]": "Oh, non!",
      "[tap on the category]": "Appuyez sur la catégorie dans laquelle vous souhaitez déplacer cette carte.",
      "[overall answer x y pages z]": "Pour valider la totalité du cours, vous devez lire au moins {questionCountToReachMasteryScore} page(s) de contenu sur {affectProgressQuestionsCount} ({masteryScoreValue}%)",
      "[you must correctly answer X questions out of Y]": "Vous devez répondre correctement à {correctQuestionsCount} question(s) sur {totalQuestionsCount} pour réussir cette étape.",
      "[you need to complete X out of Y items successfully]": "Vous devez compléter {correctQuestionsCount} élément(s) sur {totalQuestionsCount} pour réussir cette section.",
      "[you have read X out of Y pages]": "Vous avez lu {correctQuestionsCount} page(s) sur {totalQuestionsCount}.",
      "[you must read X out of Y pages]": "Vous devez lire {correctQuestionsCount} page(s) sur {totalQuestionsCount} pour réussir cette étape.",
      "[you have correctly completed X items out of Y]": "Vous avez validé {correctQuestionsCount} élément(s) sur {totalQuestionsCount}.",
      "[you must correctly complete X items out of Y]": "Vous devez valider {correctQuestionsCount} élément(s) sur {totalQuestionsCount} pour réussir cette étape.",
      "[you have not passed this course]": "Vous n'avez pas réussi cette formation.",
      "[you have completed X out of Y sections]": "Vous avez validé {correctSectionsCount} section(s) sur {totalSectionsCount}.",
      "[you must complete X out of Y sections]": "Vous devez valider {correctSectionsCount} section(s) sur {totalSectionsCount} pour réussir cette étape.",
      "[you need to read X out of Y content pages]": "Vous devez lire {correctQuestionsCount} page(s) de contenu sur {totalQuestionsCount} pour réussir cette section.",
      "[end of section]": "Fin de la section",
      "[card sorting card aria]": "Tri des cartes. Utilisez les flèches pour naviguer ou appuyez sur Entrée pour déplacer la carte.",
      "[press enter to select]": "Appuyez sur Entrée pour sélectionner.",
      "[press enter on the category]": "Il y a {x} catégories au total. Appuyez sur Tab pour passer à la catégorie suivante et appuyez sur Entrée pour déplacer la carte dans la catégorie sélectionnée.",
      "[time limit warn]": "Le minuteur démarrera une fois que vous aurez cliqué sur « Je suis prêt »",
      "[You have X minutes to complete this course]": "Vous disposez de <strong>{x} minute(s)</strong> pour terminer ce cours"
    },
    "companyCustomTranslations": {}
  },
  "courseNavigationMenu": {
    "selected": "collapseByDefault"
  },
  "saveProgressCrossDevice": {
    "enabled": true
  },
  "loginViaSocialMedia": {
    "enabled": true
  },
  "conductLearnerSatisfactionSurvey": {
    "enabled": true
  },
  "allowUsersToDownloadCertificates": {
    "enabled": false
  },
  "resultsTracking": {
    "enabled": true
  },
  "allowUserToSkipTrackingAndTracing": {
    "enabled": false
  },
  "allowScoringOfContentPages": {
    "enabled": false
  },
  "xApi": {
    "selectedLrs": "default",
    "lrs": {
      "uri": "",
      "credentials": {
        "username": "",
        "password": ""
      },
      "authenticationRequired": false
    },
    "allowedVerbs": [
      "started",
      "experienced",
      "mastered",
      "answered",
      "passed",
      "progressed",
      "failed"
    ]
  },
  "masteryScore": {
    "score": 100,
    "isOverall": false
  },
  "showContentPages": {
    "enabled": true
  },
  "showLearningHints": {
    "enabled": true
  },
  "submitAnswers": {
    "selected": "afterEveryQuestion"
  },
  "numberOfAttempts": {
    "isLimited": false,
    "attemptsLimit": 3
  },
  "answersFromPreviousAttempt": {
    "selected": "reset"
  },
  "answerOptionsOrder": {
    "selected": "setByAuthor"
  },
  "questionPool": {
    "enabled": false,
    "size": 10,
    "subset": {
      "type": "sameOnEveryAttempt",
      "randomizeQuestionOrder": false
    }
  },
  "timer": {
    "enabled": false,
    "time": {
      "hours": 0,
      "minutes": 30,
      "seconds": 0
    }
  },
  "showCorrectAnswers": {
    "enabled": false
  }
}